
<script>

$(function () {
    'use strict';

	//'<?=$this->baseUrl().'/../'.'uploader/uploader.php'?>'

  $('#fileupload').fileupload({
		url: '<?=$this->baseUrl().'/../'.'uploader/?dir='.$this->directories['dirdemande'].'&demande_codedem='.$this->directories['demande_codedem'];?>',
		
		 disableImageResize: /Android(?!.*Chrome)|Opera/
         .test(window.navigator.userAgent),
         maxFileSize: 999000,
         acceptFileTypes: /(\.|\/)(gif|jpe?g|png|pdf)$/i
	}).on('fileuploadsubmit', function (e, data) {
		data.formData = data.context.find(':input').serializeArray();
	});

    // Enable iframe cross-domain access via redirect option:
    $('#fileupload').fileupload(
        'option',
        'redirect',
        window.location.href.replace(
            /\/[^\/]*$/,
            '/cors/result.html?%s'
        )
    );

    if (window.location.hostname === 'blueimp.github.io') {
        // Demo settings:
        $('#fileupload').fileupload('option', {
            url: '<?=$this->baseUrl().'/../'.'uploader/'?>',
            // Enable image resizing, except for Android and Opera,
            // which actually support image resizing, but fail to
            // send Blob objects via XHR requests:
            disableImageResize: /Android(?!.*Chrome)|Opera/
                .test(window.navigator.userAgent),
            maxFileSize: 999000,
            acceptFileTypes: /(\.|\/)(gif|jpe?g|png|pdf)$/i
        });
        // Upload server status check for browsers with CORS support:
        if ($.support.cors) {
            $.ajax({
                url: '<?=$this->baseUrl().'/../'.'uploader/?dir='.$this->directories['dirdemande'].'&demande_codedem='.$this->directories['demande_codedem'];?>',
                type: 'HEAD'
            }).fail(function () {
                $('<div class="alert alert-danger"/>')
                    .text('Upload server currently unavailable - ' +
                            new Date())
                    .appendTo('#fileupload');
            });
        }
    } else {
        // Load existing files:
        $('#fileupload').addClass('fileupload-processing');
        $.ajax({
            // Uncomment the following to send cross-domain cookies:
            //xhrFields: {withCredentials: true},
            url: $('#fileupload').fileupload('option', 'url'),
            dataType: 'json',
            context: $('#fileupload')[0]
        }).always(function () {
            $(this).removeClass('fileupload-processing');
        }).done(function (result) {
            $(this).fileupload('option', 'done')
                .call(this, $.Event('done'), {result: result});
        });
    }



});
	

</script>

<?php
$this->headTitle('Détails du dossier de la Demande: ') ;
$form = $this->form;
?>
<div class="page-header">
   <h1>Détails du dossier de la demande : </h1>
</div>

<form class="form-horizontal" method="post" action="<?php echo $this->url(); ?>">
    <?php
    /* @var $form Zend_Form */
    foreach ($form->getElements() as $element):
        /* @var $element Zend_Form_Element */
        $errors = $element->getMessages();
        $elementName = $element->getName();
        ?>
        <div class="control-group<?php if ($errors) echo ' error'; ?>">
            <?php if ($element->getType() != 'Zend_Form_Element_Button'): ?>
                <label class="control-label" for="<?php echo $element->getId(); ?>"><?php echo $element->getLabel(); ?></label>
            <?php endif; ?>
            <div class="controls">
                <?php echo $element->renderViewHelper(); ?>
                <?php if ($errors): ?>
                    <span class="help-inline"><?php echo implode(', ', $errors); ?></span>
                <?php endif; ?>
                <?php if ('submit' == $elementName): ?>
                    <a class="btn" href="<?php echo $this->url(array('module' => 'admin','controller' => 'demande'), null, true); ?>">Cancel</a>
                    <?php endif; ?>
            </div>
        </div>
        <?php
        endforeach;
        ?>
</form>




 <form id="fileupload" action="<?=$this->baseUrl().'/../uploader/uploader.php'?>" method="POST" enctype="multipart/form-data">
        <div >
		<!-- Redirect browsers with JavaScript disabled to the origin page -->
        <noscript><input type="hidden" name="redirect" value="https://blueimp.github.io/jQuery-File-Upload/"></noscript>
        <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
		
        <div class="row fileupload-buttonbar" style="display:none;">
            <div class="col-lg-7">
                <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span>Add files...</span>
                    <input type="file" name="files[]" multiple>
                </span>
                <button type="submit" class="btn btn-primary start">
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start upload</span>
                </button>
                <button type="reset" class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel upload</span>
                </button>
                <button type="button" class="btn btn-danger delete">
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
                <input type="checkbox" class="toggle">
                <!-- The global file processing state -->
                <span class="fileupload-process"></span>
            </div>
            <!-- The global progress state -->
            <div class="col-lg-5 fileupload-progress fade" style="  margin-left: 10px;">
                <!-- The global progress bar -->
                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                    <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                </div>
                <!-- The extended global progress state -->
                <div class="progress-extended">&nbsp;</div>
            </div>
        </div>
        <!-- The table listing the files available for upload/download -->
        <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
		<div>
    </form>
    <br>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Demo Notes</h3>
        </div>
        <div class="panel-body">
            <ul>
                <li>The maximum file size for uploads in this demo is <strong>999 KB</strong> (default file size is unlimited).</li>
                <li>Only image files (<strong>JPG, GIF, PNG, PDF</strong>) are allowed in this demo (by default there is no file type restriction).</li>
               
                <li>You can <strong>drag &amp; drop</strong> files from your desktop .</li>
               
            </ul>
        </div>
    </div>
</div>
<!-- The blueimp Gallery widget -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>
<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
		<td>
		<label class="title">
			<span>Title:</span><br>
			<input name="title[]" class="form-control">
		</label>
		<label class="description">
			<span>Description:</span><br>
			<input name="description[]" class="form-control">
			<input type="hidden" name="dirdemande" value="<?=$this->directories['dirdemande']?>">
			<input type="hidden" name="urldemande" value="<?=$this->baseUrl()?>">
			<input type="hidden" name="demande_codedem" value="<?=$this->directories['demande_codedem']?>">
		</label>
		</td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start" disabled>
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
                {% } %}
            </span>
        </td>
		<td>
			<p class="title"><strong>{%=file.title||''%}</strong></p>
			<p class="description">{%=file.description||''%}</p>
			
			<input type="hidden" name="dirdemande" value="<?=$this->directories['dirdemande']?>">
			<input type="hidden" name="urldemande" value="<?=$this->baseUrl()?>">
			<input type="hidden" name="demande_codedem" value="<?=$this->directories['demande_codedem']?>">
			
		</td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                    <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
                <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td style="display:none;">
            {% if (file.deleteUrl) { %}
                <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
                <input type="checkbox" name="delete" value="1" class="toggle">
            {% } else { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>