<?php
$this->headTitle('Etudiant Management');
?>
<?php
$tableVille = new Application_Model_Ville_DbTable();
$tableEtablissement = new Application_Model_Etablissement_DbTable();
?>

<style>
.col-lg-3 {
  width: 44%;
}
.panel {font-size: 22px;}

.col-xs-3 {
  width: 58%;
}

</style>




<div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><strong  font-size: 32px;>Espace étudiant</strong></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>


			
			
			
			
			
			
	 <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="">Année d'études </i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"></div>
                                    <div></div>
                                </div>
                            </div>
                        </div>
                       <a href="<?=$this->url(array("module"=>"default","action"=>"index","controller"=>"Etudes","cin"=>$this->etudiantstore['cin']),null,true);?>">
						    <div class="panel-footer">
                                <span class="pull-left">Voir détails</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
	
	 
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-red">
                        <div class="panel-heading">
                            <div class="row">
                               <div class="col-xs-3">
                                    <i class="">Modifier votre profile personnel</i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"></div>
                                    <div></div>
                                </div>
                            </div>
                        </div>
                       <a href="<?=$this->url(array("module"=>"default","action"=>"update","controller"=>"etudiant","cin"=>$this->etudiantstore['cin']),null,true)?>">
								<div class="panel-footer">
                                <span class="pull-left">Voir détails</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
				
				 <div class="col-lg-3 col-md-6">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            <div class="row">
                               <div class="col-xs-3">
                                    <i class="">  Modifier Paramêtres de connexion</i>
                                </div>
                                <div class="col-xs-9 text-right">
                                   <div class="huge"><i class=""><img src="<?php echo $this->baseUrl().'/images/login.png';?>" width="80px"/></i></div>
                                    <div></div>
                                </div>
                            </div>
                        </div>
                        <a href="<?=$this->url(array("module"=>"default","action"=>"updatelogin","controller"=>"etudiant","cin"=>$this->etudiantstore['cin']),null,true)?>">
								<div class="panel-footer">
                                <span class="pull-left">Voir détails</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
	
	 </div>
	
			
			
			
			