<?php
$this->headTitle('Demande Management');
?>
<?php
$tableAnneeUniversitaire = new Application_Model_AnneeUniversitaire_DbTable();
$tableEtudiant = new Application_Model_Etudiant_DbTable();
?>

<script type="text/javascript">
function toggleCheckboxes(source)
{
    var checkboxes = document.getElementsByName('del_id[]');
    for (var i = 0; i < checkboxes.length; i++)
    {
        checkboxes[i].checked = source.checked;
    }
}

function updateFilters(paramName, paramValue)
{
    var newQuery = [];
    var args = {};
    var query = location.search.indexOf('?') > -1 ? location.search.substring(1).split('&') : [];

    for (var pairIndex = 0; pairIndex < query.length; pairIndex++) {
        var param = query[pairIndex].split('=');
        args[param[0]] = param[1];
    }

    args[paramName] = paramValue;
    for (var key in args)
    {
        newQuery.push(key + '=' + encodeURIComponent(args[key]));
    }

    self.location.href = '?' + newQuery.join('&');
}
</script>

<div class="page-header">
   <h1>Demande Management</h1>
</div>

<div class="pull-right">
<a class="btn btn-info" href="<?php echo $this->url(array('module' => 'default','controller' => 'demande', 'action' => 'index'), null, true); ?>"><i class=" icon-refresh icon-white"></i> Reset Filters</a>
<a class="btn btn-success" href="<?php echo $this->url(array('module' => 'default','controller' => 'demande', 'action' => 'create'), null, true); ?>"><i class="icon-plus icon-white"></i> Add New</a></div><br />

<form class="form form-inline" method="get" action="<?php echo $this->url(array('module' => 'default','controller' => 'demande', 'action' => 'index'), null, true); ?>">
<div>
<input class="input-medium search-query" placeholder="Keywords..." type="text" name="_kw" value="<?php echo htmlspecialchars($this->param_kw); ?>" /> 
<?php echo $this->formSelect('_sm', $this->param_sm, array(), array (
  'all' => 'All',
  'descriptif' => 'Descriptif',
)); ?>
    
<button class="btn" type="submit"><i class="icon-search"></i> Search</button>
</div>
</form>

<form method="post" action="<?php echo $this->url(array('module' => 'default','controller' => 'demande', 'action' => 'delete'), null, true); ?>" onsubmit="return confirm('Delete selected rows?');">
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th><input type="checkbox" onchange="toggleCheckboxes(this);" /></th>
            <th<?php if ('codedem' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Codedem 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'codedem', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'codedem', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th<?php if ('type_demande' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Type Demande 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'type_demande', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'type_demande', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                <?php echo $this->formSelect('type_demande', $this->paramtype_demande, array('onchange' => 'updateFilters(\'type_demande\', this.options[this.selectedIndex].value)'), array (
  '' => '- - Change - -',
  'Reorientation' => 'Reorientation',
  'Mutation' => 'Mutation',
  'Chparcours' => 'Chparcours',
  'Retrait' => 'Retrait',
  'Report' => 'Report',
)); ?>
            </th>
            <th<?php if ('annee_universitaire' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Annee Universitaire 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'annee_universitaire', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'annee_universitaire', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                <?php
    echo $this->formSelect('annee_universitaire', $this->paramannee_universitaire, array('onchange' => 'updateFilters(\'annee_universitaire\', this.options[this.selectedIndex].value)'), array('' => '- - Change - -') + $tableAnneeUniversitaire->fetchPairs());
?>
            </th>
            <th<?php if ('CIN' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                CIN 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'CIN', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'CIN', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                <?php
    echo $this->formSelect('CIN', $this->paramCIN, array('onchange' => 'updateFilters(\'CIN\', this.options[this.selectedIndex].value)'), array('' => '- - Change - -') + $tableEtudiant->fetchPairs());
?>
            </th>
            <th<?php if ('etat' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Etat 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'etat', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'etat', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                <?php echo $this->formSelect('etat', $this->parametat, array('onchange' => 'updateFilters(\'etat\', this.options[this.selectedIndex].value)'), array (
  '' => '- - Change - -',
  'Refuser' => 'Refuser',
  'Accepter' => 'Accepter',
)); ?>
            </th>
            <th<?php if ('descriptif' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Descriptif 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'descriptif', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'descriptif', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th<?php if ('date_demande' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Date Demande 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'date_demande', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'date_demande', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th><input type="checkbox" onchange="toggleCheckboxes(this);" /></th>
            <th<?php if ('codedem' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Codedem 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'codedem', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'codedem', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th<?php if ('type_demande' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Type Demande 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'type_demande', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'type_demande', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                <?php echo $this->formSelect('type_demande', $this->paramtype_demande, array('onchange' => 'updateFilters(\'type_demande\', this.options[this.selectedIndex].value)'), array (
  '' => '- - Change - -',
  'Reorientation' => 'Reorientation',
  'Mutation' => 'Mutation',
  'Chparcours' => 'Chparcours',
  'Retrait' => 'Retrait',
  'Report' => 'Report',
)); ?>
            </th>
            <th<?php if ('annee_universitaire' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Annee Universitaire 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'annee_universitaire', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'annee_universitaire', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                <?php
    echo $this->formSelect('annee_universitaire', $this->paramannee_universitaire, array('onchange' => 'updateFilters(\'annee_universitaire\', this.options[this.selectedIndex].value)'), array('' => '- - Change - -') + $tableAnneeUniversitaire->fetchPairs());
?>
            </th>
            <th<?php if ('CIN' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                CIN 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'CIN', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'CIN', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                <?php
    echo $this->formSelect('CIN', $this->paramCIN, array('onchange' => 'updateFilters(\'CIN\', this.options[this.selectedIndex].value)'), array('' => '- - Change - -') + $tableEtudiant->fetchPairs());
?>
            </th>
            <th<?php if ('etat' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Etat 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'etat', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'etat', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                <?php echo $this->formSelect('etat', $this->parametat, array('onchange' => 'updateFilters(\'etat\', this.options[this.selectedIndex].value)'), array (
  '' => '- - Change - -',
  'Refuser' => 'Refuser',
  'Accepter' => 'Accepter',
)); ?>
            </th>
            <th<?php if ('descriptif' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Descriptif 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'descriptif', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'descriptif', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th<?php if ('date_demande' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Date Demande 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'date_demande', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'date_demande', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th>Actions</th>
        </tr>
    </tfoot>
    <tbody>
<?php foreach ($this->paginator as $row): ?>
        <tr>
            <td align="center"><input type="checkbox" name="del_id[]" value="<?php echo $row->codedem; ?>" /></td>
            <td align="right"><?php echo htmlspecialchars($row->codedem); ?></td>
            <td><?php echo htmlspecialchars($row->type_demande); ?></td>
            <td><?php     $linkedRow = $tableAnneeUniversitaire->find($row->annee_universitaire)->current();
    if ($linkedRow) {
        echo htmlspecialchars($linkedRow->getZodekenAutoLabel());
    } else {
        echo htmlspecialchars($linkedRow->annee_universitaire), ' (unlinked)';
    } ?></td>
            <td><?php     $linkedRow = $tableEtudiant->find($row->CIN)->current();
    if ($linkedRow) {
        echo htmlspecialchars($linkedRow->getZodekenAutoLabel());
    } else {
        echo htmlspecialchars($linkedRow->CIN), ' (unlinked)';
    } ?></td>
            <td><?php echo htmlspecialchars($row->etat); ?></td>
            <td><?php echo htmlspecialchars($row->descriptif); ?></td>
            <td><?php echo htmlspecialchars($row->date_demande); ?></td>
            <td align="center"><a href="<?php echo $this->url(array('module' => 'default','controller' => 'demande', 'action' => 'update', 'id' => $row->codedem), null, true); ?>">Edit</a> 
    - <a onclick="return confirm('Confirm deletion!');" href="<?php echo $this->url(array('module' => 'default','controller' => 'demande', 'action' => 'delete', 'del_id' => $row->codedem), null, true); ?>">Delete</a></td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table><br />
<button class="btn btn-danger" type="submit"><i class=" icon-trash icon-white"></i> Delete Selected Rows</button>
</form>

<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'pagination_control.phtml');