<?php
$this->headTitle('Files Management');
?>
<?php
$tableDemande = new Application_Model_Demande_DbTable();
?>

<script type="text/javascript">
function toggleCheckboxes(source)
{
    var checkboxes = document.getElementsByName('del_id[]');
    for (var i = 0; i < checkboxes.length; i++)
    {
        checkboxes[i].checked = source.checked;
    }
}

function updateFilters(paramName, paramValue)
{
    var newQuery = [];
    var args = {};
    var query = location.search.indexOf('?') > -1 ? location.search.substring(1).split('&') : [];

    for (var pairIndex = 0; pairIndex < query.length; pairIndex++) {
        var param = query[pairIndex].split('=');
        args[param[0]] = param[1];
    }

    args[paramName] = paramValue;
    for (var key in args)
    {
        newQuery.push(key + '=' + encodeURIComponent(args[key]));
    }

    self.location.href = '?' + newQuery.join('&');
}
</script>

<div class="page-header">
   <h1>Files Management</h1>
</div>

<div class="pull-right">
<a class="btn btn-info" href="<?php echo $this->url(array('module' => 'default','controller' => 'files', 'action' => 'index'), null, true); ?>"><i class=" icon-refresh icon-white"></i> Reset Filters</a>
<a class="btn btn-success" href="<?php echo $this->url(array('module' => 'default','controller' => 'files', 'action' => 'create'), null, true); ?>"><i class="icon-plus icon-white"></i> Add New</a></div><br />

<form class="form form-inline" method="get" action="<?php echo $this->url(array('module' => 'default','controller' => 'files', 'action' => 'index'), null, true); ?>">
<div>
<input class="input-medium search-query" placeholder="Keywords..." type="text" name="_kw" value="<?php echo htmlspecialchars($this->param_kw); ?>" /> 
<?php echo $this->formSelect('_sm', $this->param_sm, array(), array (
  'all' => 'All',
  'name' => 'Name',
  'type' => 'Type',
  'url' => 'Url',
  'title' => 'Title',
  'description' => 'Description',
)); ?>
    
<button class="btn" type="submit"><i class="icon-search"></i> Search</button>
</div>
</form>

<form method="post" action="<?php echo $this->url(array('module' => 'default','controller' => 'files', 'action' => 'delete'), null, true); ?>" onsubmit="return confirm('Delete selected rows?');">
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th><input type="checkbox" onchange="toggleCheckboxes(this);" /></th>
            <th<?php if ('id' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Id 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'id', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'id', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th<?php if ('name' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Name 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'name', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'name', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th<?php if ('size' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Size 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'size', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'size', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th<?php if ('type' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Type 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'type', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'type', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th<?php if ('url' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Url 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'url', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'url', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th<?php if ('title' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Title 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'title', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'title', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th<?php if ('description' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Description 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'description', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'description', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th<?php if ('date' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Date 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'date', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'date', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th<?php if ('codedem' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Codedem 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'codedem', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'codedem', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                <?php
    echo $this->formSelect('codedem', $this->paramcodedem, array('onchange' => 'updateFilters(\'codedem\', this.options[this.selectedIndex].value)'), array('' => '- - Change - -') + $tableDemande->fetchPairs());
?>
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th><input type="checkbox" onchange="toggleCheckboxes(this);" /></th>
            <th<?php if ('id' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Id 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'id', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'id', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th<?php if ('name' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Name 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'name', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'name', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th<?php if ('size' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Size 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'size', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'size', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th<?php if ('type' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Type 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'type', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'type', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th<?php if ('url' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Url 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'url', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'url', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th<?php if ('title' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Title 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'title', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'title', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th<?php if ('description' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Description 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'description', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'description', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th<?php if ('date' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Date 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'date', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'date', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th<?php if ('codedem' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Codedem 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'codedem', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'codedem', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                <?php
    echo $this->formSelect('codedem', $this->paramcodedem, array('onchange' => 'updateFilters(\'codedem\', this.options[this.selectedIndex].value)'), array('' => '- - Change - -') + $tableDemande->fetchPairs());
?>
            </th>
            <th>Actions</th>
        </tr>
    </tfoot>
    <tbody>
<?php foreach ($this->paginator as $row): ?>
        <tr>
            <td align="center"><input type="checkbox" name="del_id[]" value="<?php echo $row->id; ?>" /></td>
            <td align="right"><?php echo htmlspecialchars($row->id); ?></td>
            <td><?php echo htmlspecialchars($row->name); ?></td>
            <td align="right"><?php echo htmlspecialchars($row->size); ?></td>
            <td><?php echo htmlspecialchars($row->type); ?></td>
            <td><?php echo htmlspecialchars($row->url); ?></td>
            <td><?php echo htmlspecialchars($row->title); ?></td>
            <td><?php echo htmlspecialchars(mb_substr($row->description, 0, 100)), '...'; ?></td>
            <td><?php echo htmlspecialchars($row->date); ?></td>
            <td><?php     $linkedRow = $tableDemande->find($row->codedem)->current();
    if ($linkedRow) {
        echo htmlspecialchars($linkedRow->getZodekenAutoLabel());
    } else {
        echo htmlspecialchars($linkedRow->codedem), ' (unlinked)';
    } ?></td>
            <td align="center"><a href="<?php echo $this->url(array('module' => 'default','controller' => 'files', 'action' => 'update', 'id' => $row->id), null, true); ?>">Edit</a> 
    - <a onclick="return confirm('Confirm deletion!');" href="<?php echo $this->url(array('module' => 'default','controller' => 'files', 'action' => 'delete', 'del_id' => $row->id), null, true); ?>">Delete</a></td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table><br />
<button class="btn btn-danger" type="submit"><i class=" icon-trash icon-white"></i> Delete Selected Rows</button>
</form>

<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'pagination_control.phtml');