<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Bootstrap Admin Theme</title>

    <!-- Bootstrap Core CSS -->
 
    <?php $this->headLink()->appendStylesheet($this->baseUrl().'/bower_components/bootstrap/dist/css/bootstrap.min.css'); ?> 
    <?php $this->headScript()->appendFile($this->baseUrl().'/bower_components/bootstrap/dist/css/bootstrap.min.js'); ?>
    <!-- MetisMenu CSS -->
 
     <?php $this->headLink()->appendStylesheet($this->baseUrl().'/bower_components/metisMenu/dist/metisMenu.min.css'); ?> 
    <?php $this->headScript()->appendFile($this->baseUrl().'/bower_components/metisMenu/dist/metisMenu.min.js'); ?>
    
    
    <!-- Custom CSS -->

   <?php $this->headLink()->appendStylesheet($this->baseUrl().'/dist/css/sb-admin-2.css') ?>
     <?php $this->headScript()->appendFile($this->baseUrl().'/dist/css/sb-admin-2.js'); ?>
    <!-- Morris Charts CSS -->
    
<?php $this->headLink()->appendStylesheet($this->baseUrl().'/bower_components/morrisjs/morris.css') ?>
<?php $this->headScript()->appendFile($this->baseUrl().'/bower_components/morrisjs/morris.js'); ?> 
    <!-- Custom Fonts -->
    
<?php $this->headLink()->appendStylesheet($this->baseUrl().'/bower_components/font-awesome/css/font-awesome.min.css') ?>
<?php $this->headScript()->appendFile($this->baseUrl().'/bower_components/font-awesome/css/font-awesome.min.js'); ?> 
    <?php echo $this->headLink();?>
    <?php echo $this->headScript();?>
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Bienvenue</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>Read All Messages</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-messages -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-tasks fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-tasks">
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 1</strong>
                                        <span class="pull-right text-muted">40% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                            <span class="sr-only">40% Complete (success)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 2</strong>
                                        <span class="pull-right text-muted">20% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                            <span class="sr-only">20% Complete</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 3</strong>
                                        <span class="pull-right text-muted">60% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                            <span class="sr-only">60% Complete (warning)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <p>
                                        <strong>Task 4</strong>
                                        <span class="pull-right text-muted">80% Complete</span>
                                    </p>
                                    <div class="progress progress-striped active">
                                        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                            <span class="sr-only">80% Complete (danger)</span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>See All Tasks</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-tasks -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-comment fa-fw"></i> New Comment
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                                    <span class="pull-right text-muted small">12 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-envelope fa-fw"></i> Message Sent
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-tasks fa-fw"></i> New Task
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-upload fa-fw"></i> Server Rebooted
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>See All Alerts</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-alerts -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="<?=$this->url(array("action"=>"admini","controller"=>"Administra"))?>"><i class="fa fa-dashboard fa-fw"></i> <i>Espace Admin</i></a>
                            
                            <a href="<?=$this->url(array("action"=>"acc","controller"=>"Acceuil"))?>"><i class="fa fa-dashboard fa-fw"></i> <i>Acceder</i></a>
                            <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> <i>Espace Etudiant</i></a>
                            <ul class="nav nav-second-level collapse in">
                            
                           <li><a href="#"><span class=""></span>
                           <b><i>Deposer Demande  </i></b></a>
                           
                       <ul class="nav nav-second-level">
                       <a href="<?=$this->url(array("action"=>"create","controller"=>"Reorientation"))?>">demande de Reorientation</a><br>
                          <a href="<?=$this->url(array("action"=>"create","controller"=>"Mutation"))?>">demande de Mutation</a><br>
                          <a href="<?=$this->url(array("action"=>"create","controller"=>"Retrait"))?>">demande de Retrait d'inscription</a><br>
                          <a href="<?=$this->url(array("action"=>"create","controller"=>"Report"))?>">demande de Report d'inscription</a>
                          <a href="<?=$this->url(array("action"=>"create","controller"=>"Chparcours"))?>">demande de changement de parcours</a></ul></li>
      
                       <li><a href=""><b><i>Consulter parcours pedagogiques</i></b></li>
                       
                        <li><a href=""><b><i>Consulter proclamations administratives</i></b></li>
                        
                        <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> <i>Espace Agent EER</i></a>
                         <li><a href="#"><span class=""></span>
                           <b><i>Gerer la liste des etudiants </i></b></a>
                           
                       <ul class="nav nav-second-level">
                       <a href="<?=$this->url(array("action"=>"create","controller"=>"Etudiant"))?>">Ajouter</a><br>
                          <a href="<?=$this->url(array("action"=>"delete","controller"=>"Etudiant"))?>">Supprimer</a><br>
                          <a href="<?=$this->url(array("action"=>"update","controller"=>"Etudiant"))?>">Rechercher</a><br>
                          
                        
                        <li><a href="#"><span class=""></span>
                           <b><i>Gerer les demandes de mouvements </i></b></a>
                           
                 
                        <li><a href="#"><span class=""></span>
                           <b><i>Generer des statistiques</i></b></a>
                           
                           <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> <i>Espace Agent UMA</i></a>
                         <li><a href="#"><span class=""></span>
                           <b><i>Gerer demande </i></b></a>
                           
                       <ul class="nav nav-second-level">
                       <a href="<?=$this->url(array("action"=>"create","controller"=>"Demande"))?>">Consulter</a><br>
                       <a href="<?=$this->url(array("action"=>"update","controller"=>"Demande"))?>">Rechercher</a><br>
                          
                        
                        <li><a href="#"><span class=""></span>
                           <b><i>Saisir proclamations administratives </i></b></a></li>
                           
                 
                        <li><a href="#"><span class=""></span>
                           <b><i>Exporter listes des etudiants</i></b></a></li>
                           
                           
                      <a href="index.html"><i class="fa fa-dashboard fa-fw"></i> <i>Espace Responsable</i></a> 
                         <ul class="nav nav-second-level collapse in">
                            
                           <li><a href="#"><span class=""></span>
                           <b><i>Consulter les demandes deposees  </i></b></a>
                           
                           
                         
                      <b><i> <a href="<?=$this->url(array("action"=>"#","controller"=>"#"))?>">Consulter les demandes deposees</a></i></b><br>
                      
                         
                           
                           
                            <!-- /.nav-second-level -->
                        </li>
                       
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            
     <?php echo $this->layout()->content ?>
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="../bower_components/jquery/dist/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="../bower_components/metisMenu/dist/metisMenu.min.js"></script>

    <!-- Morris Charts JavaScript -->
    <script src="../bower_components/raphael/raphael-min.js"></script>
    <script src="../bower_components/morrisjs/morris.min.js"></script>
    <script src="../js/morris-data.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="../dist/js/sb-admin-2.js"></script>

</body>

</html>
