<?php if($this->demandeexist) {?>
<div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><strong   font-size: 32px;>Veuillez consulter les détails de votre demande</strong></h1>
                </div>
                <!-- /.col-lg-12 -->
 </div>
	
	 <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="">Demande <?=$this->demandeexist['type_demande']?></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"></div>
                                    <div></div>
                                </div>
                            </div>
                        </div>
                       <a href="<?=$this->url(array("module"=>"default","action"=>"index","controller"=>$this->demandeexist['type_demande']))?>">
						    <div class="panel-footer">
                                <span class="pull-left">Voir détails</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
	
	
	
	
	
	
	
	
	
	
	
<?php } else {?>
<?php
$this->headTitle('Create Demande');
$form = $this->form;
?>


<div class="page-header">
   <h1>Créer une Demande</h1>
</div>

<form class="form-horizontal" method="post" action="<?php echo $this->url(); ?>">
    <?php
    /* @var $form Zend_Form */
    foreach ($form->getElements() as $element):
        /* @var $element Zend_Form_Element */
        $errors = $element->getMessages();
        $elementName = $element->getName();
        ?>
        <div class="control-group<?php if ($errors) echo ' error'; ?>">
            <?php if ($element->getType() != 'Zend_Form_Element_Button'): ?>
                <label class="control-label" for="<?php echo $element->getId(); ?>"><?php echo $element->getLabel(); ?></label>
            <?php endif; ?>
            <div class="controls">
                <?php echo $element->renderViewHelper(); ?>
                <?php if ($errors): ?>
                    <span class="help-inline"><?php echo implode(', ', $errors); ?></span>
                <?php endif; ?>
                <?php if ('submit' == $elementName): ?>
                    <a class="btn" href="<?php echo $this->url(array('module' => 'default','controller' => 'demande'), null, true); ?>">Cancel</a>
                    <?php endif; ?>
            </div>
        </div>
        <?php
        endforeach;
        ?>
</form>
    
	<?php } ?>