<?php
$this->headTitle('AnneeUniversitaire Management');
?>

<script type="text/javascript">
function toggleCheckboxes(source)
{
    var checkboxes = document.getElementsByName('del_id[]');
    for (var i = 0; i < checkboxes.length; i++)
    {
        checkboxes[i].checked = source.checked;
    }
}

function updateFilters(paramName, paramValue)
{
    var newQuery = [];
    var args = {};
    var query = location.search.indexOf('?') > -1 ? location.search.substring(1).split('&') : [];

    for (var pairIndex = 0; pairIndex < query.length; pairIndex++) {
        var param = query[pairIndex].split('=');
        args[param[0]] = param[1];
    }

    args[paramName] = paramValue;
    for (var key in args)
    {
        newQuery.push(key + '=' + encodeURIComponent(args[key]));
    }

    self.location.href = '?' + newQuery.join('&');
}
</script>

<div class="page-header">
   <h1>AnneeUniversitaire Management</h1>
</div>

<div class="pull-right">
<a class="btn btn-info" href="<?php echo $this->url(array('module' => 'default','controller' => 'annee-universitaire', 'action' => 'index'), null, true); ?>"><i class=" icon-refresh icon-white"></i> Reset Filters</a>
<a class="btn btn-success" href="<?php echo $this->url(array('module' => 'default','controller' => 'annee-universitaire', 'action' => 'create'), null, true); ?>"><i class="icon-plus icon-white"></i> Add New</a></div><br />

<form class="form form-inline" method="get" action="<?php echo $this->url(array('module' => 'default','controller' => 'annee-universitaire', 'action' => 'index'), null, true); ?>">
<div>
<input class="input-medium search-query" placeholder="Keywords..." type="text" name="_kw" value="<?php echo htmlspecialchars($this->param_kw); ?>" /> 
<?php echo $this->formSelect('_sm', $this->param_sm, array(), array (
  'all' => 'All',
  'annee' => 'Annee',
)); ?>
    
<button class="btn" type="submit"><i class="icon-search"></i> Search</button>
</div>
</form>

<form method="post" action="<?php echo $this->url(array('module' => 'default','controller' => 'annee-universitaire', 'action' => 'delete'), null, true); ?>" onsubmit="return confirm('Delete selected rows?');">
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th><input type="checkbox" onchange="toggleCheckboxes(this);" /></th>
            <th<?php if ('idannee' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Idannee 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'idannee', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'idannee', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th<?php if ('annee' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Annee 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'annee', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'annee', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th><input type="checkbox" onchange="toggleCheckboxes(this);" /></th>
            <th<?php if ('idannee' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Idannee 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'idannee', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'idannee', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th<?php if ('annee' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Annee 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'annee', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'annee', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                
            </th>
            <th>Actions</th>
        </tr>
    </tfoot>
    <tbody>
<?php foreach ($this->paginator as $row): ?>
        <tr>
            <td align="center"><input type="checkbox" name="del_id[]" value="<?php echo $row->idannee; ?>" /></td>
            <td align="right"><?php echo htmlspecialchars($row->idannee); ?></td>
            <td><?php echo htmlspecialchars($row->annee); ?></td>
            <td align="center"><a href="<?php echo $this->url(array('module' => 'default','controller' => 'annee-universitaire', 'action' => 'update', 'id' => $row->idannee), null, true); ?>">Edit</a> 
    - <a onclick="return confirm('Confirm deletion!');" href="<?php echo $this->url(array('module' => 'default','controller' => 'annee-universitaire', 'action' => 'delete', 'del_id' => $row->idannee), null, true); ?>">Delete</a></td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table><br />
<button class="btn btn-danger" type="submit"><i class=" icon-trash icon-white"></i> Delete Selected Rows</button>
</form>

<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'pagination_control.phtml');