<?php
$this->headTitle('Report Management');
?>
<?php
$tableDemande = new Application_Model_Demande_DbTable();
$tableParcours = new Application_Model_Parcours_DbTable();
?>

<script type="text/javascript">
function toggleCheckboxes(source)
{
    var checkboxes = document.getElementsByName('del_id[]');
    for (var i = 0; i < checkboxes.length; i++)
    {
        checkboxes[i].checked = source.checked;
    }
}

function updateFilters(paramName, paramValue)
{
    var newQuery = [];
    var args = {};
    var query = location.search.indexOf('?') > -1 ? location.search.substring(1).split('&') : [];

    for (var pairIndex = 0; pairIndex < query.length; pairIndex++) {
        var param = query[pairIndex].split('=');
        args[param[0]] = param[1];
    }

    args[paramName] = paramValue;
    for (var key in args)
    {
        newQuery.push(key + '=' + encodeURIComponent(args[key]));
    }

    self.location.href = '?' + newQuery.join('&');
}
</script>

<div class="page-header">
   <h1>Report Management</h1>
</div>

<div class="pull-right">
<a class="btn btn-info" href="<?php echo $this->url(array('module' => 'admin','controller' => 'report', 'action' => 'index'), null, true); ?>"><i class=" icon-refresh icon-white"></i> Reset Filters</a>
<a class="btn btn-success" href="<?php echo $this->url(array('module' => 'admin','controller' => 'report', 'action' => 'create'), null, true); ?>"><i class="icon-plus icon-white"></i> Add New</a></div><br />

<form class="form form-inline" method="get" action="<?php echo $this->url(array('module' => 'admin','controller' => 'report', 'action' => 'index'), null, true); ?>">
<div>
<input class="input-medium search-query" placeholder="Keywords..." type="text" name="_kw" value="<?php echo htmlspecialchars($this->param_kw); ?>" /> 
<?php echo $this->formSelect('_sm', $this->param_sm, array(), array (
  'all' => 'All',
)); ?>
    
<button class="btn" type="submit"><i class="icon-search"></i> Search</button>
</div>
</form>

<form method="post" action="<?php echo $this->url(array('module' => 'admin','controller' => 'report', 'action' => 'delete'), null, true); ?>" onsubmit="return confirm('Delete selected rows?');">
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th><input type="checkbox" onchange="toggleCheckboxes(this);" /></th>
            <th<?php if ('codedem' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Codedem 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'codedem', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'codedem', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                <?php
    echo $this->formSelect('codedem', $this->paramcodedem, array('onchange' => 'updateFilters(\'codedem\', this.options[this.selectedIndex].value)'), array('' => '- - Change - -') + $tableDemande->fetchPairs());
?>
            </th>
            <th<?php if ('section_actuelle' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Section Actuelle 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'section_actuelle', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'section_actuelle', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                <?php
    echo $this->formSelect('section_actuelle', $this->paramsection_actuelle, array('onchange' => 'updateFilters(\'section_actuelle\', this.options[this.selectedIndex].value)'), array('' => '- - Change - -') + $tableParcours->fetchPairs());
?>
            </th>
            <th<?php if ('niveau_actuelle' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Niveau Actuelle 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'niveau_actuelle', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'niveau_actuelle', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                <?php echo $this->formSelect('niveau_actuelle', $this->paramniveau_actuelle, array('onchange' => 'updateFilters(\'niveau_actuelle\', this.options[this.selectedIndex].value)'), array (
  '' => '- - Change - -',
  '1ere année' => '1ere année',
  '2eme année' => '2eme année',
  '3eme année' => '3eme année',
)); ?>
            </th>
            <th<?php if ('causereport' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Causereport 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'causereport', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'causereport', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                <?php echo $this->formSelect('causereport', $this->paramcausereport, array('onchange' => 'updateFilters(\'causereport\', this.options[this.selectedIndex].value)'), array (
  '' => '- - Change - -',
  'Santé' => 'Santé',
  'Personnel' => 'Personnel',
)); ?>
            </th>
            <th<?php if ('causerepperso' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Causerepperso 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'causerepperso', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'causerepperso', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                <?php echo $this->formSelect('causerepperso', $this->paramcauserepperso, array('onchange' => 'updateFilters(\'causerepperso\', this.options[this.selectedIndex].value)'), array (
  '' => '- - Change - -',
  'Oui' => 'Oui',
  'Non' => 'Non',
)); ?>
            </th>
            <th<?php if ('causerepsante' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Causerepsante 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'causerepsante', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'causerepsante', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                <?php echo $this->formSelect('causerepsante', $this->paramcauserepsante, array('onchange' => 'updateFilters(\'causerepsante\', this.options[this.selectedIndex].value)'), array (
  '' => '- - Change - -',
  'Oui' => 'Oui',
  'Non' => 'Non',
)); ?>
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th><input type="checkbox" onchange="toggleCheckboxes(this);" /></th>
            <th<?php if ('codedem' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Codedem 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'codedem', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'codedem', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                <?php
    echo $this->formSelect('codedem', $this->paramcodedem, array('onchange' => 'updateFilters(\'codedem\', this.options[this.selectedIndex].value)'), array('' => '- - Change - -') + $tableDemande->fetchPairs());
?>
            </th>
            <th<?php if ('section_actuelle' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Section Actuelle 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'section_actuelle', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'section_actuelle', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                <?php
    echo $this->formSelect('section_actuelle', $this->paramsection_actuelle, array('onchange' => 'updateFilters(\'section_actuelle\', this.options[this.selectedIndex].value)'), array('' => '- - Change - -') + $tableParcours->fetchPairs());
?>
            </th>
            <th<?php if ('niveau_actuelle' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Niveau Actuelle 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'niveau_actuelle', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'niveau_actuelle', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                <?php echo $this->formSelect('niveau_actuelle', $this->paramniveau_actuelle, array('onchange' => 'updateFilters(\'niveau_actuelle\', this.options[this.selectedIndex].value)'), array (
  '' => '- - Change - -',
  '1ere année' => '1ere année',
  '2eme année' => '2eme année',
  '3eme année' => '3eme année',
)); ?>
            </th>
            <th<?php if ('causereport' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Causereport 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'causereport', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'causereport', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                <?php echo $this->formSelect('causereport', $this->paramcausereport, array('onchange' => 'updateFilters(\'causereport\', this.options[this.selectedIndex].value)'), array (
  '' => '- - Change - -',
  'Santé' => 'Santé',
  'Personnel' => 'Personnel',
)); ?>
            </th>
            <th<?php if ('causerepperso' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Causerepperso 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'causerepperso', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'causerepperso', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                <?php echo $this->formSelect('causerepperso', $this->paramcauserepperso, array('onchange' => 'updateFilters(\'causerepperso\', this.options[this.selectedIndex].value)'), array (
  '' => '- - Change - -',
  'Oui' => 'Oui',
  'Non' => 'Non',
)); ?>
            </th>
            <th<?php if ('causerepsante' == $this->sortField) echo ' class="sort-field sort-', htmlspecialchars($this->param_so), '"'; ?>>
                Causerepsante 
                <a href='<?php echo $this->url($_GET + array('_sf' => 'causerepsante', '_so' => 'asc')); ?>'><i class='icon-arrow-up'></i></a>
                <a href='<?php echo $this->url($_GET + array('_sf' => 'causerepsante', '_so' => 'desc')); ?>'><i class='icon-arrow-down'></i></a>
                <?php echo $this->formSelect('causerepsante', $this->paramcauserepsante, array('onchange' => 'updateFilters(\'causerepsante\', this.options[this.selectedIndex].value)'), array (
  '' => '- - Change - -',
  'Oui' => 'Oui',
  'Non' => 'Non',
)); ?>
            </th>
            <th>Actions</th>
        </tr>
    </tfoot>
    <tbody>
<?php foreach ($this->paginator as $row): ?>
        <tr>
            <td align="center"><input type="checkbox" name="del_id[]" value="<?php echo $row->codedem; ?>" /></td>
            <td><?php     $linkedRow = $tableDemande->find($row->codedem)->current();
    if ($linkedRow) {
        echo htmlspecialchars($linkedRow->getZodekenAutoLabel());
    } else {
        echo htmlspecialchars($linkedRow->codedem), ' (unlinked)';
    } ?></td>
            <td><?php     $linkedRow = $tableParcours->find($row->section_actuelle)->current();
    if ($linkedRow) {
        echo htmlspecialchars($linkedRow->getZodekenAutoLabel());
    } else {
        echo htmlspecialchars($linkedRow->section_actuelle), ' (unlinked)';
    } ?></td>
            <td><?php echo htmlspecialchars($row->niveau_actuelle); ?></td>
            <td><?php echo htmlspecialchars($row->causereport); ?></td>
            <td><?php echo htmlspecialchars($row->causerepperso); ?></td>
            <td><?php echo htmlspecialchars($row->causerepsante); ?></td>
            <td align="center"><a href="<?php echo $this->url(array('module' => 'admin','controller' => 'report', 'action' => 'update', 'id' => $row->codedem), null, true); ?>">Edit</a> 
    - <a onclick="return confirm('Confirm deletion!');" href="<?php echo $this->url(array('module' => 'admin','controller' => 'report', 'action' => 'delete', 'del_id' => $row->codedem), null, true); ?>">Delete</a></td>
        </tr>
<?php endforeach; ?>
    </tbody>
</table><br />
<button class="btn btn-danger" type="submit"><i class=" icon-trash icon-white"></i> Delete Selected Rows</button>
</form>

<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'pagination_control.phtml');