<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>UMA</title>

    <!-- Bootstrap Core CSS -->
 
    <?php $this->headLink()->appendStylesheet($this->baseUrl().'/bower_components/bootstrap/dist/css/bootstrap.min.css'); ?>
    <?php $this->headLink()->appendStylesheet($this->baseUrl().'/bower_components/metisMenu/dist/metisMenu.min.css'); ?>  
    <?php 
    $this->headScript()->appendFile($this->baseUrl().'/bower_components/jquery/dist/jquery.min.js');
    $this->headScript()->appendFile($this->baseUrl().'/bower_components/bootstrap/dist/js/bootstrap.min.js'); ?>
    <!-- MetisMenu CSS -->
 
     
    <?php $this->headScript()->appendFile($this->baseUrl().'/bower_components/metisMenu/dist/metisMenu.min.js'); ?>
    
    
    
   <?php $this->headLink()->appendStylesheet($this->baseUrl().'/dist/css/sb-admin-2.css') ?>
     <?php $this->headScript()->appendFile($this->baseUrl().'/dist/js/sb-admin-2.js'); ?>
    <!-- Morris Charts CSS -->
    <!-- Custom CSS -->
	<style>
			.hidden {
			    display: none;
			}
    </style>
	
	
 
    
<?php //$this->headLink()->appendStylesheet($this->baseUrl().'/bower_components/morrisjs/morris.css') ?>
<?php //$this->headScript()->appendFile($this->baseUrl().'/bower_components/morrisjs/morris.js'); ?> 
    <!-- Custom Fonts -->
    
<?php $this->headLink()->appendStylesheet($this->baseUrl().'/bower_components/font-awesome/css/font-awesome.min.css') ?>


<?php 
     
     $this->headScript()->appendFile($this->baseUrl().'/bower_components/metisMenu/dist/metisMenu.min.js');
     $this->headScript()->appendFile($this->baseUrl().'/bower_components/bootstrap/dist/js/bootstrap.min.js');
     
     $this->headScript()->appendFile($this->baseUrl().'/bower_components/raphael/raphael-min.js');
     $this->headScript()->appendFile($this->baseUrl().'/bower_components/morrisjs/morris.min.js');
    // $this->headScript()->appendFile($this->baseUrl().'/js/morris-data.js');
 	

	
	 $this->headScript()->appendFile($this->baseUrl().'/bower_components/blueimp-file-upload/js/vendor/jquery.ui.widget.js');
	
	 //$this->headScript()->appendFile($this->baseUrl().'/bower_components/blueimp-file-upload/jquery-ui/jquery-ui.min.js');
	 //$this->headScript()->appendFile($this->baseUrl().'/bower_components/blueimp-file-upload/jquery-ui/jquery.min.js');
	 
	 $this->headScript()->appendFile($this->baseUrl().'/bower_components/blueimp-file-upload/js/jquery.iframe-transport.js');
	 $this->headScript()->appendFile($this->baseUrl().'/bower_components/blueimp-file-upload/js/vendor/jquery.ui.widget.js');
	 $this->headScript()->appendFile($this->baseUrl().'/bower_components/blueimp-file-upload/js/jquery.fileupload.js');
	 $this->headScript()->appendFile($this->baseUrl().'/bower_components/blueimp-file-upload/js/jquery.fileupload-process.js');
	 $this->headScript()->appendFile($this->baseUrl().'/bower_components/blueimp-file-upload/js/jquery.fileupload-image.js');
	 $this->headScript()->appendFile($this->baseUrl().'/bower_components/blueimp-file-upload/js/jquery.fileupload-audio.js');
	 $this->headScript()->appendFile($this->baseUrl().'/bower_components/blueimp-file-upload/js/jquery.fileupload-video.js');
	 $this->headScript()->appendFile($this->baseUrl().'/bower_components/blueimp-file-upload/js/jquery.fileupload-validate.js');
	 $this->headScript()->appendFile($this->baseUrl().'/bower_components/blueimp-file-upload/js/jquery.fileupload-ui.js');
	 //$this->headScript()->appendFile($this->baseUrl().'/bower_components/blueimp-file-upload/js/main.js');
	 
	 
	//$this->headScript()->appendFile($this->baseUrl().'/bower_components/blueimp-file-upload/blueimp-js/load-image.all.min.js');
	//$this->headScript()->appendFile($this->baseUrl().'/bower_components/blueimp-file-upload/blueimp-js/canvas-to-blob.min.js');
	$this->headScript()->appendFile($this->baseUrl().'/bower_components/blueimp-file-upload/blueimp-js/jquery.blueimp-gallery.min.js');
	//$this->headScript()->appendFile($this->baseUrl().'/bower_components/blueimp-file-upload/blueimp-js/tmpl.min.js');
	 
	 $this->headLink()->appendStylesheet($this->baseUrl().'/bower_components/blueimp-file-upload/css/jquery.fileupload.css'); 
	 $this->headLink()->appendStylesheet($this->baseUrl().'/bower_components/blueimp-file-upload/css/jquery.fileupload-ui.css');
	 $this->headLink()->appendStylesheet($this->baseUrl().'/bower_components/blueimp-file-upload/css/style.css');
	 
	 //$this->headLink()->appendStylesheet($this->baseUrl().'/bower_components/blueimp-file-upload/css/jquery.fileupload-noscript.css'); 
	 //$this->headLink()->appendStylesheet($this->baseUrl().'/bower_components/blueimp-file-upload/css/jquery.fileupload-ui-noscript.css'); 
	 //$this->headLink()->appendStylesheet($this->baseUrl().'/bower_components/blueimp-file-upload/css/demo.css'); 
	 $this->headLink()->appendStylesheet($this->baseUrl().'/bower_components/blueimp-file-upload/css/blueimp-gallery.min.css'); 
	 
	 
	 $this->headScript()->appendFile($this->baseUrl().'/bower_components/excellentexport/excellentexport.js');
	
	 ?>
	 
	<!-- blueimp Gallery styles -->
		  <script src="//blueimp.github.io/JavaScript-Templates/js/tmpl.min.js"></script>
		  <!-- The Load Image plugin is included for the preview images and image resizing functionality -->
		  <script src="//blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js"></script>
		  <!-- The Canvas to Blob plugin is included for image resizing functionality -->
		  <script src="//blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js"></script>
		
	
		<!-- 
			<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
		
			<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		
			<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
		
		Bootstrap JS is not required, but included for the responsive demo navigation -->
		
		
	 <!-- jQuery UI styles 
	 		
	 <link rel="stylesheet" href="//blueimp.github.io/Gallery/css/blueimp-gallery.min.css">

	 
	 
	  $this->headLink()->appendStylesheet('http://blueimp.github.io/Gallery/css/blueimp-gallery.min.css'); 
	 	<link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/themes/dark-hive/jquery-ui.css" id="theme">
	 -->

	<!-- Demo styles -->

	<!--[if lte IE 8]>
	<link rel="stylesheet" href="css/demo-ie8.css">
	<![endif]-->
	<style>
	/* Adjust the jQuery UI widget font-size: */
	.ui-widget {
		font-size: 0.95em;
	}
	</style>
	<!-- blueimp Gallery styles -->

	<!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->

	<!-- CSS adjustments for browsers with JavaScript disabled -->
	<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
	<!-- The Canvas to Blob plugin is included for image resizing functionality -->
	<!-- Bootstrap JS is not required, but included for the responsive demo navigation -->
	<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
	<!-- The basic File Upload plugin -->
	<!-- The File Upload processing plugin -->
	<!-- The File Upload image preview & resize plugin -->
	<!-- The File Upload audio preview plugin -->
	<!-- The File Upload video preview plugin -->
	<!-- The File Upload validation plugin -->
	<!-- The File Upload user interface plugin -->
	<!-- The main application script -->
	

	 
   
    <?php echo $this->headLink();?>
    <?php echo $this->headScript();?>
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>   


<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?=$this->url(array("module"=>"admin","action"=>"index","controller"=>"index"),null,true)?>">Bienvenue</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-envelope fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-messages">
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <strong>John Smith</strong>
                                    <span class="pull-right text-muted">
                                        <em>Yesterday</em>
                                    </span>
                                </div>
                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a class="text-center" href="#">
                                <strong>Read All Messages</strong>
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </li>
                    </ul>
                    <!-- /.dropdown-messages -->
                </li>
                <!-- /.dropdown -->
               
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false">
                        <i class="fa fa-user fa-fw">
                        
                        </i> 
							<?php echo $this->etudiantstore['login'];?>
						<i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="<?=$this->url(array("module"=>"admin","action"=>"update","controller"=>"authentif","login"=>$this->etudiantstore['login']),null,true)?>"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="<?=$this->url(array("module"=>"admin","action"=>"logout","controller"=>"Gestauth"))?>">
						<i class="fa fa-sign-out fa-fw"></i> Déconnecter</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

                      
                
                
            <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li class="sidebar-search">
                    <div class="input-group custom-search-form">
                        <input type="text" class="form-control" placeholder="Search...">
                                    <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                    </div>
                    <!-- /input-group -->
                </li>
                <li>
                    <a href="<?=$this->url(array("module"=>"admin","action"=>"index","controller"=>"etudiant"),null,true)?>"><i class="fa fa-user fa-fw"></i> Liste des étudiant</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-edit fa-fw"></i> Liste des demandes<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse">
                        <li>
                            <a href="<?=$this->url(array("action"=>"index","controller"=>"Demande",'type_demande'=>'Reorientation'))?>">demandes de Reorientation</a>
                        </li>
                        <li>
                            <a href="<?=$this->url(array("action"=>"index","controller"=>"Demande",'type_demande'=>'Mutation'))?>">demandes de Mutation</a>
                        </li>
                        <li>
                            <a href="<?=$this->url(array("action"=>"index","controller"=>"Demande",'type_demande'=>'Retrait'))?>">demandes de Retrait d'inscription</a>
                        </li>
                        <li>
                            <a href="<?=$this->url(array("action"=>"index","controller"=>"Demande",'type_demande'=>'Report'))?>">demandes de Report d'inscription</a>
                        </li>
                        <li>
                            <a href="<?=$this->url(array("action"=>"index","controller"=>"Demande",'type_demande'=>'Chparcours'))?>">demandes de changement de parcours</a>
                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
				
                 <li>
                     <a href="#"><i class="fa fa-edit fa-fw"></i> Gestion du parcours pédagogique<span class="fa arrow"></span></a>
                     
                     <ul class="nav nav-second-level collapse">
                        <li>
                            <a href="<?=$this->url(array("module"=>"admin","action"=>"index","controller"=>"mention"),null,true)?>"><i class="fa fa-user fa-fw"></i> Gestion du mention</a>
                        </li>
                        <li>
                            <a href="<?=$this->url(array("module"=>"admin","action"=>"index","controller"=>"domaine"),null,true)?>"><i class="fa fa-user fa-fw"></i> Gestion du domaine</a>
                        </li>
                        <li>
                            <a href="<?=$this->url(array("module"=>"admin","action"=>"index","controller"=>"diplome"),null,true)?>"><i class="fa fa-user fa-fw"></i> Gestion du diplome</a>
                        </li>
                        <li>
                           <a href="<?=$this->url(array("module"=>"admin","action"=>"index","controller"=>"parcours"),null,true)?>"><i class="fa fa-user fa-fw"></i> Gestion du parcours</a>
                        </li>
                        
                    </ul>
                     
                    
                </li>
                
				<?php if($this->etudiantstore['module']=='admin') {?>
                <li>
                    <a href="<?=$this->url(array("module"=>"admin","action"=>"index","controller"=>"authentif"),null,true)?>"><i class="fa fa-user fa-fw"></i> Liste des utlisateurs</a>
                </li>
				<?php }?>
               
              
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
            
               
            
            
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            
				<?php echo $this->layout()->content ?>
				
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

 

</body>

</html>







 
 
 