<?php
$this->headTitle('Create Lang');
$form = $this->form;
?>
<div class="page-header">
   <h1>Create Lang</h1>
</div>

<form class="form-horizontal" method="post" action="<?php echo $this->url(); ?>">
    <?php
    /* @var $form Zend_Form */
    foreach ($form->getElements() as $element):
        /* @var $element Zend_Form_Element */
        $errors = $element->getMessages();
        $elementName = $element->getName();
        ?>
        <div class="control-group<?php if ($errors) echo ' error'; ?>">
            <?php if ($element->getType() != 'Zend_Form_Element_Button'): ?>
                <label class="control-label" for="<?php echo $element->getId(); ?>"><?php echo $element->getLabel(); ?></label>
            <?php endif; ?>
            <div class="controls">
                <?php echo $element->renderViewHelper(); ?>
                <?php if ($errors): ?>
                    <span class="help-inline"><?php echo implode(', ', $errors); ?></span>
                <?php endif; ?>
                <?php if ('submit' == $elementName): ?>
                    <a class="btn" href="<?php echo $this->url(array('module' => 'default','controller' => 'lang'), null, true); ?>">Cancel</a>
                    <?php endif; ?>
            </div>
        </div>
        <?php
        endforeach;
        ?>
</form>
    