<?php
$this->headTitle('Détails de la Demande');

?>

<?php if($this->demandeexist) {?>




<div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header"><strong   font-size: 32px;>Etat de votre demande</strong></h1>
                </div>
                <!-- /.col-lg-12 -->
 </div>
 
 <?php if($this->demandeexist['etat']=='En Attente') {?>
	 
	<div class="alert alert-warning" role="alert">
      <strong>!</strong> Demande en cours de traitement ......
    </div>
	

	
	
 <?php }elseif($this->demandeexist['etat']=='Accepter') {?>
	<div class="alert alert-success" role="alert">
	 <strong>!</strong> Demande acceptée .
	</div>
	

 <?php }else {?>
	<div class="alert alert-danger" role="alert">
	   <strong>!</strong> Demande refusée .
	</div>
	
	 <?php if($this->demandeexist['descriptif']) { ?>
		<div class="alert alert-info" role="alert">
		  <strong>
		  <?=$this->demandeexist['descriptif'];?>
		  </strong>
		</div>
	<?php } ?>
	
 <?php }?>

	
	
<?php } ?>

